### ISSUE TITLE
TypeError: Object #<Object> has no method 'parse'

### ISSUE THREAD

**Issue by TriSysBusinessSoftware** [MicrosoftEdge/hwa-cli#10]
C:\Users\Garry\AppData\Roaming\npm\node_modules\hwa-cli\bin\src\cli.js:42
                    var filenameWithoutExt = p.parse(args[0]).name;
                                               ^
TypeError: Object #<Object> has no method 'parse'
    at Object.main (C:\Users\Garry\AppData\Roaming\npm\node_modules\hwa-cli\bin\
src\cli.js:42:48)
    at Object.<anonymous> (C:\Users\Garry\AppData\Roaming\npm\node_modules\hwa-c
li\main.js:50:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by zackhall** [comment]
Hi @TriSysBusinessSoftware, can you please post the command you were trying to run so that we can repro the issue?
